### ISSUE TITLE
Support hapi v17

### ISSUE THREAD

**Issue by felixheck** [pinojs/hapi-pino#24]
Hi there!

Because one of my plugins is relying on `hapi-pino` and I use it in several projects with the latest stuff, I was wondering if you guys already work on supporting the `v17.0.0` of `hapi` which seems to be released at 1st of November :)

Thanks and best.

**Comment by mcollina** [comment]
Not right now, but if you want to send a PR it will be extremely welcomed!

**Comment by felixheck** [comment]
Have to update my own plugins first..as soon as I have some time left :)
Thanks for your fast reply.

Would like to leave the issue opened. Maybe there's another guy having some time for the PR.

**Comment by timcosta** [comment]
Normally this is a top level issue, but I'll add it here seeing as this is already open.

### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [ ] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [ ] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [ ] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.
* This issue is being opened because your plugin is listed on the official hapi website

**Comment by mcollina** [comment]
This is done in #25. Please provide feedback, as Hapi is _very_ different.
